# golangci-lint configuration for Tempus
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags: []

linters:
  disable-all: true
  enable:
    # Critical: Bugs & Correctness only for v0.5.0
    - govet          # Vet examines Go source code
    - staticcheck    # Go static analysis
    - typecheck      # Type checking
    - gofmt          # Check formatting only
    - goimports      # Check imports only

linters-settings:
  govet:
    enable-all: false
    enable:
      - atomic
      - bools
      - buildtag
      - nilfunc
      - printf
    disable:
      - shadow       # Too many false positives
      - fieldalignment

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude staticcheck SA1019 (deprecated)
    - linters:
        - staticcheck
      text: "SA1019:"

    # Exclude staticcheck SA5011 (nil pointer checks in tests are intentional)
    - linters:
        - staticcheck
      text: "SA5011:"
      path: "_test\\.go"

  fix: false

output:
  sort-results: true
  print-issued-lines: true
  print-linter-name: true
