package templates

import (
	"encoding/json"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// ScaffoldOptions controls how GenerateScaffold creates template content.
type ScaffoldOptions struct {
	Name     string
	Language string
	Format   string // yaml (default) or json
}

// GenerateScaffold returns a template definition serialized in the requested format.
func GenerateScaffold(opts ScaffoldOptions) ([]byte, error) {
	name := strings.TrimSpace(opts.Name)
	if name == "" {
		return nil, fmt.Errorf("template name cannot be empty")
	}

	format := strings.ToLower(strings.TrimSpace(opts.Format))
	if format == "" {
		format = "yaml"
	}
	if format != "yaml" && format != "json" {
		return nil, fmt.Errorf("unsupported format %q (use yaml or json)", format)
	}

	lang := strings.ToLower(strings.TrimSpace(opts.Language))
	if lang == "" {
		lang = "en"
	}

	labels := scaffoldStrings(lang)

	dd := DataDrivenTemplate{
		SchemaVersion:    1,
		Name:             name,
		Description:      labels.TemplateDescription,
		FilenameTemplate: fmt.Sprintf("%s-{{slug title}}.ics", slugify(name)),
		Fields: []Field{
			{Key: "title", Name: labels.FieldTitle, Type: "text", Required: true},
			{Key: "start_time", Name: labels.FieldStartTime, Type: "datetime", Required: true},
			{Key: "duration", Name: labels.FieldDuration, Type: "text", Default: "45m"},
			{Key: "timezone", Name: labels.FieldTimezone, Type: "timezone", Default: "UTC"},
			{Key: "notes", Name: labels.FieldNotes, Type: "text"},
			{Key: "rrule", Name: labels.FieldRRule, Type: "text", Description: labels.RRuleHint},
			{Key: "alarms", Name: labels.FieldAlarms, Type: "alarms", Description: labels.AlarmsHint},
		},
	}

	dd.Output = OutputTemplate{
		StartField:      "start_time",
		DurationField:   "duration",
		StartTZField:    "timezone",
		EndTZField:      "timezone",
		RRuleField:      "rrule",
		AlarmsField:     "alarms",
		SummaryTmpl:     labels.SummaryTemplate,
		DescriptionTmpl: labels.DescriptionTemplate,
		Categories:      []string{labels.Category},
	}

	switch format {
	case "json":
		return json.MarshalIndent(dd, "", "  ")
	default:
		return yaml.Marshal(dd)
	}
}

type scaffoldLocaleStrings struct {
	TemplateDescription string
	FieldTitle          string
	FieldStartTime      string
	FieldDuration       string
	FieldTimezone       string
	FieldNotes          string
	FieldRRule          string
	FieldAlarms         string
	RRuleHint           string
	AlarmsHint          string
	SummaryTemplate     string
	DescriptionTemplate string
	Category            string
}

func scaffoldStrings(lang string) scaffoldLocaleStrings {
	spanish := scaffoldLocaleStrings{
		TemplateDescription: "Plantilla generada por tempus init",
		FieldTitle:          "Título",
		FieldStartTime:      "Inicio (YYYY-MM-DD HH:MM)",
		FieldDuration:       "Duración (ej. 30m, 1h)",
		FieldTimezone:       "Zona horaria",
		FieldNotes:          "Notas",
		FieldRRule:          "Recurrencia (RRULE)",
		FieldAlarms:         "Recordatorios (15m,1h)",
		RRuleHint:           "Opcional: FREQ=DAILY;COUNT=5",
		AlarmsHint:          "Opcional: duraciones separadas por coma (ej. 15m,1h)",
		SummaryTemplate:     "Evento: {{title}}",
		DescriptionTemplate: "{{#notes}}Notas: {{notes}}{{/notes}}",
		Category:            "Personalizado",
	}

	portuguese := scaffoldLocaleStrings{
		TemplateDescription: "Modelo gerado por tempus init",
		FieldTitle:          "Título",
		FieldStartTime:      "Início (YYYY-MM-DD HH:MM)",
		FieldDuration:       "Duração (ex. 30m, 1h)",
		FieldTimezone:       "Fuso horário",
		FieldNotes:          "Notas",
		FieldRRule:          "Recorrência (RRULE)",
		FieldAlarms:         "Lembretes (15m,1h)",
		RRuleHint:           "Opcional: FREQ=DAILY;COUNT=5",
		AlarmsHint:          "Opcional: durações separadas por vírgula (ex. 15m,1h)",
		SummaryTemplate:     "Evento: {{title}}",
		DescriptionTemplate: "{{#notes}}Notas: {{notes}}{{/notes}}",
		Category:            "Personalizado",
	}

	english := scaffoldLocaleStrings{
		TemplateDescription: "Template scaffold generated by tempus init",
		FieldTitle:          "Title",
		FieldStartTime:      "Start Time (YYYY-MM-DD HH:MM)",
		FieldDuration:       "Duration (e.g. 30m, 1h)",
		FieldTimezone:       "Timezone",
		FieldNotes:          "Notes",
		FieldRRule:          "Recurrence (RRULE)",
		FieldAlarms:         "Alarms (15m,1h)",
		RRuleHint:           "Optional: FREQ=WEEKLY;COUNT=5",
		AlarmsHint:          "Optional: comma-separated durations (e.g. 15m,1h)",
		SummaryTemplate:     "Event: {{title}}",
		DescriptionTemplate: "{{#notes}}Notes: {{notes}}{{/notes}}",
		Category:            "Custom",
	}

	switch lang {
	case "es":
		return spanish
	case "pt", "pt-br", "pt-pt", "pt_br", "pt_pt":
		return portuguese
	default:
		return english
	}
}
